### ISSUE TITLE
Not able to delete Requested Items

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#101]
Bug of the day : 
I'm not able anymore to delete a Requested Item. 
If I try with the "Skill View" where I can directly act on the requested item or if I do a request from the "Public view" and then try to accept this request, both won't work. 
See video below : 
https://www.dropbox.com/s/13qcs1fhod7e6n0/Bug%20delete%20RI.avi?dl=0

Cheers,

**Comment by fabian** [comment]
I was able to reproduce this problem and found a way to create a requested item that cannot be deleted. The problem is in the logic of the code, I will look for a solution.

Steps to create a undeletable item:

- Create requested item with new supplied item
  - A new supplied item with description ID 1 is created, user generated true
  - A new requested item with description ID 2 is created
- Edit description of requested item
  - [Supplied item gets description ID 2](https://github.com/worldskills/API-Infrastructure-List/blob/c3032366d35747de8e87d9b427d9a7f2511de538/src/main/java/org/worldskills/api/il/rest/RequestedItemResource.java#L983), same as requested item
- Edit supplied item
  - Supplied item still has description ID 2
  - Requested item also has description ID 2, is now user generated false

When trying to delete the requested item, the description cannot be deleted, as it still is used by the supplied item.

**Comment by fabian** [comment]
I think we should change [the code](https://github.com/worldskills/API-Infrastructure-List/blob/c3032366d35747de8e87d9b427d9a7f2511de538/src/main/java/org/worldskills/api/il/rest/RequestedItemResource.java#L983) and make sure requested and supplied items never share the same description ID.

@Joni-Aaltonen  There is also a migration needed which splits existing requested and supplied items with the same description ID.

**Comment by Joni-Aaltonen** [comment]
Yeah a clear bug, I'm on it

**Comment by fabian** [comment]
@ailtisWSFR You should now be able to delete the item. Please reopen if you cannot delete it.

**Comment by ailtisWSFR** [comment]
@fabian Perfect, just tested and it does work. Thanks!
