### ISSUE TITLE
Track history

### ISSUE THREAD

**Issue by fabian** [worldskills/worldskills-infrastructure-list#28]
> - Track all changes (who made change, timestamp, etc)
> - Be able to see status of IL at any point in the past
> - Ability to add notes/comments when changing status

**Comment by PierreAnctil** [comment]
> Track all changes (who made change, timestamp, etc)

All tables should be tracked except external synchronized tables (event, member_reg_position, person, position, sector, skill, user_role and ws_entity).

Envers should be used :
http://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#envers

It should be extended to track user name
http://ignaciosuay.com/how-to-use-hibernate-envers-to-audit-data-including-username/

> Be able to see status of IL at any point in the past

@fabian Should an UI be developed for that or will the data being queryable in DB be sufficient?

> Ability to add notes/comments when changing status

Changing the requested item status should trigger the appearance of an additional optional field "Status change reason".

Since audit table will then be active, we just need to store the last change reason in the `requested_item` table. Reasons for previous changes will be available in the audit table.

**Comment by fabian** [comment]
Yes, I think we should have some kind of user interface to see the IL at a certain point in time - for administrators at least. Maybe simply with a calendar icon in the public IL view?

**Comment by gbervik** [comment]
@PierreAnctil Keep in mind that Envers will tell you when and how individual objects changed, but it won't give you any context or the business logic behind the changes. For example, if the supplier of an item changes how do you know if it was part of a mass-edit, or maybe a bug? I think we need to keep a log of the **actions** taken by the user, as well as what changed at a database level.

Also we want to know the `person_id` rather than the username.

I agree that we need a UI, and it needs handle things like:
- show all changes to a particular item (what changed, who changed them, and when)
- show all actions by a particular user within a specified time span
- show changes to a particular skill (or meeting room, etc) within a specified time span

**Comment by PierreAnctil** [comment]
@Joni-Aaltonen I'm not sure that rollbacking a single table really makes sense since all tables are related. As an example you cannot rollback requested_items without supplied items, skills, etc.

@gbervik Since some API routes (like supplied item edit) can be called from several pages, I think the only way to have the **actions** tracked would be for the front to send explicitly the action to the API. Or did I misunderstand the concept of *action*?
If this is always sent in the same request header, any method could access it. So it could be added to Envers revisions along with the person_id (see this example to extend Envers revision: (http://ignaciosuay.com/how-to-use-hibernate-envers-to-audit-data-including-username/) ). I'm currently trying to PoC it.

Other solutions to have more flexibility would be 
- hibernate listeners
- triggers (pro: support direct queries)
Both those solutions will be very time consuming, and since we would need to manage our tracking tables manually, we would need to create entities and description (hbm) for each tracking table.

**Comment by gbervik** [comment]
@PierreAnctil I was only referring to actions as far as the API is concerned. It doesn't matter if the supplied item edit is being called from several pages, as long as we know that the changes that occurred happened during that edit action. For example, I assume that editing a single item uses a different route to mass edits?

**Comment by PierreAnctil** [comment]
@gbervik no routes are currently not always different. Mass edit for requested items and supplied items call multiple times the single edit route. But that's clearly not optimal so that could be the opportunity to change that.

**Comment by PierreAnctil** [comment]
@gbervik No currently that is not always the case. The mass edit for requested items & supplied items call the edit route in a loop. However I agree this is far from optimal and that could be the opportunity to change that.

**Comment by fabian** [comment]
> Needs to be ready for CPW

**Comment by PierreAnctil** [comment]
We pushed a proof of concept of envers with user tracking in branch [feature/#40](https://github.com/worldskills/API-Infrastructure-List/tree/feature/%2340).
The changes in table `item_category` are tracked and a `person_id` is saved each time.
An action could be saved in the same way.
The username is just a constant for now since changed would probably be required in [WorldSkills-Java-Lib](https://github.com/worldskills/WorldSkills-Java-Lib) to make the `person_id` of the connected user available in envers listener.

**Comment by gbervik** [comment]
@PierreAnctil we have used envers with user tracking in another project. You can get the user information like this:
```
public void newRevision(Object revisionEntity) 
{
	ILRevisionEntity iLrevisionEntity = (ILRevisionEntity) revisionEntity;

	RequestData requestData = GuiceInjector.INSTANCE.getInjector().getInstance(RequestData.class);
	UserSession userSession = requestData.getSession();

	// if null, the change is likely to be from a rabbitMQ message
	if(userSession != null) 
		iLrevisionEntity.setPersonId(userSession.getUser().getPersonId());
}
```
The challenge is going to be handling all the use cases for querying and displaying the data.
