### ISSUE TITLE
Recommend an addition / modification on public view

### ISSUE THREAD

**Issue by ailtisWSFR** [worldskills/worldskills-infrastructure-list#90]
Hi, 

There is a bug when our Experts and WorkShop Managers wish to us the "Recommend an addition" or "Recommend a modification" tool. 
See screenshot below and video. 
![bug](https://user-images.githubusercontent.com/39295271/40537851-4711faf2-6010-11e8-9049-46068f9663ac.png)

Thanks in advance for a quick solution since this tool is essential for us at the moment.

Regards,
Arthur

**Comment by ailtisWSFR** [comment]
url of the video : 

https://www.dropbox.com/s/k2dp8j6jn3ag2tt/20180525_104055.mp4?dl=0

**Comment by PierreAnctil** [comment]
@ailtisWSFR are you sure this is the right video? There just seems to be a lost connexion issue in the one you provided.

**Comment by ailtisWSFR** [comment]
@PierreAnctil Yes I'm sure, just try and you will see by yourself. The connexion don't get lost, your still connected. This problem appears to all Experts and WorkShop Managers.

**Comment by fabian** [comment]
@PierreAnctil I just had a quick look on production and it seems the problem is with this wrong request to `https://api.worldskills.org/il/items/undefined/supplied_items/?search=Foo`:

![screenshot 2018-05-25 13 35 43](https://user-images.githubusercontent.com/13346/40542454-8a00a204-6020-11e8-83d7-d4970018f6e2.png)

Looking at the code it seems `$scope.event_id` is not defined for Experts viewing the public print view as it usually gets set when selecting the current role in the code. Maybe try to use `$state.params.eventId` instead:

https://github.com/worldskills/worldskills-infrastructure-list/blob/00a210c914ecca27f1747b4ecaaea009a83b417f/app/scripts/controllers/recommendeditemaside.js#L21

Are you okay with taking care of this or should I try to put together a fix?

**Comment by ailtisWSFR** [comment]
Just to be precise : 
My screenshot = bug with the tool "Recommend a modification"
The video = bug with the tool "Recommend an addition"

**Comment by PierreAnctil** [comment]
Fix submitted for review

**Comment by fabian** [comment]
@PierreAnctil The Supplied Item search call works now correct, however they still get HTTP 401 Forbidden, because they don't have permission to search Supplied Items:

https://github.com/worldskills/API-Infrastructure-List/blob/35daa7a048b50164f00f9d91f518a41b38057375/src/main/java/org/worldskills/api/il/rest/SuppliedItemResource.java#L189-L190

**Comment by fabian** [comment]
Deployed to production.
